stages:
  - verify
  - e2e

image: cypress/base:10

jest-unit-tests:
  stage: verify
  before_script:
    - yarn
  script:
    - yarn test

check-build:
  stage: verify
  before_script:
    - yarn
  script:
    - yarn build

cypress-e2e-tests:
  image: cypress/base:10
  stage: e2e
  before_script:
    - npm install
    - yarn
    - yarn start &
  script:
    - yarn cypress:ci
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
