stages:
  - verify
  - e2e
  - deploy

image: cypress/base:10

deploy_staging:
  stage: deploy
  before_script:
    - npm i -g netlify
    - yarn
  script:
    - echo "Deploy a review app"
    - yarn deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.nora.netlify.com
#
# lint:
#   stage: verify
#   before_script:
#     - yarn
#   script:
#     - yarn lint

# jest-unit-tests:
#   stage: verify
#   before_script:
#     - yarn
#   script:
#     - yarn test

# check-build:
#   stage: verify
#   before_script:
#     - yarn
#   script:
#     - yarn build

# cypress-e2e-tests:
#   stage: e2e
#   before_script:
#     - yarn
#     - npm install
#     - yarn start &
#   script:
#     - yarn cypress:ci
#   artifacts:
#     expire_in: 1 day
#     when: always
#     paths:
#       - cypress/screenshots
#       - cypress/videos
