stages:
  - verify

image: node:20-alpine

vitest-unit-tests:
  stage: verify
  before_script:
    - npm ci
  script:
    - npm run test run

check-build:
  stage: verify
  before_script:
    - npm ci
  script:
    - npm run build

lint:
  stage: verify
  before_script:
    - npm ci
  script:
    - npm run lint
