language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - ~/.cache
    - ~/.npm
    - ~/.yarn
  override:
    - npm ci
    - npm run cy:verify
before_script:
  - yarn start --silent &
script:
  - yarn
  - yarn verify
  - yarn coveralls
