language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - ~/.cache
    - ~/.npm
    - ~/.yarn
  override:
    - npm ci
    - npm run cy:verify

script:
  - yarn
  - yarn start:cypress --silent &
  - yarn verify
  - yarn coveralls
  - kill $(jobs -p) || true
