export const SET_ACTIVE_SCREEN = 'SET_ACTIVE_SCREEN'
export type SET_ACTIVE_SCREEN = typeof SET_ACTIVE_SCREEN

export const ADD_CORRECT_ANSWER = 'ADD_CORRECT_ANSWER'
export type ADD_CORRECT_ANSWER = typeof ADD_CORRECT_ANSWER

export const ADD_WRONG_ANSWER = 'ADD_WRONG_ANSWER'
export type ADD_WRONG_ANSWER = typeof ADD_WRONG_ANSWER

export const UPDATE_SOLUTION = 'UPDATE_SOLUTION'
export type UPDATE_SOLUTION = typeof UPDATE_SOLUTION

export const RESTART = 'RESTART'
export type RESTART = typeof RESTART
