name: CI

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: jakejarvis/lighthouse-action@master
        with:
          url: "https://deploy-preview-${{ github.number }}.--nora.netlify.com/"
